import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { generatePayoutBatch } from "@/lib/actions/payouts";

export default async function PayoutsPage() {
  const batches = await prisma.payoutBatchSnapshot.findMany({
    orderBy: { generatedAt: "desc" },
    include: { generatedByAdmin: true, _count: { select: { items: true } } },
  });

  const unbatchedCount = await prisma.referral.count({
    where: { status: "VERIFIED", payoutBatchItem: null },
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">Payout Batches</h1>
          <p className="text-sm text-neutral-500">
            {unbatchedCount} verified referral(s) ready to be batched.
          </p>
        </div>
        <form action={generatePayoutBatch}>
          <button
            type="submit"
            className="rounded-md bg-neutral-900 px-3 py-1.5 text-sm font-medium text-white dark:bg-neutral-50 dark:text-neutral-900"
          >
            Generate Batch
          </button>
        </form>
      </div>

      <div className="overflow-x-auto rounded-lg border border-neutral-200 dark:border-neutral-800">
        <table className="w-full text-left text-sm">
          <thead className="border-b border-neutral-200 bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-900">
            <tr>
              <th className="px-4 py-2 font-medium">Period</th>
              <th className="px-4 py-2 font-medium">Items</th>
              <th className="px-4 py-2 font-medium">Generated by</th>
              <th className="px-4 py-2 font-medium">Generated at</th>
            </tr>
          </thead>
          <tbody>
            {batches.map((batch) => (
              <tr
                key={batch.id}
                className="border-b border-neutral-100 last:border-0 hover:bg-neutral-50 dark:border-neutral-900 dark:hover:bg-neutral-900"
              >
                <td className="px-4 py-2">
                  <Link href={`/payouts/${batch.id}`} className="font-medium hover:underline">
                    {batch.periodLabel}
                  </Link>
                </td>
                <td className="px-4 py-2">{batch._count.items}</td>
                <td className="px-4 py-2">{batch.generatedByAdmin.name}</td>
                <td className="px-4 py-2 text-neutral-500">
                  {batch.generatedAt.toLocaleString()}
                </td>
              </tr>
            ))}
            {batches.length === 0 && (
              <tr>
                <td colSpan={4} className="px-4 py-8 text-center text-neutral-500">
                  No payout batches yet.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
