import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function PayoutBatchDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const batch = await prisma.payoutBatchSnapshot.findUnique({
    where: { id },
    include: {
      generatedByAdmin: true,
      items: { orderBy: { createdAt: "asc" } },
    },
  });

  if (!batch) notFound();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">Payout Batch — {batch.periodLabel}</h1>
          <p className="text-sm text-neutral-500">
            Generated by {batch.generatedByAdmin.name} on{" "}
            {batch.generatedAt.toLocaleString()}
          </p>
        </div>
        <a
          href={`/api/payouts/${batch.id}/csv`}
          className="rounded-md bg-neutral-900 px-3 py-1.5 text-sm font-medium text-white dark:bg-neutral-50 dark:text-neutral-900"
        >
          Download CSV
        </a>
      </div>

      <div className="overflow-x-auto rounded-lg border border-neutral-200 dark:border-neutral-800">
        <table className="w-full text-left text-sm">
          <thead className="border-b border-neutral-200 bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-900">
            <tr>
              <th className="px-4 py-2 font-medium">Referrer wallet</th>
              <th className="px-4 py-2 font-medium">Referred wallet</th>
              <th className="px-4 py-2 font-medium">Type</th>
              <th className="px-4 py-2 font-medium">Tier %</th>
              <th className="px-4 py-2 font-medium">Verified at</th>
            </tr>
          </thead>
          <tbody>
            {batch.items.map((item) => (
              <tr
                key={item.id}
                className="border-b border-neutral-100 last:border-0 dark:border-neutral-900"
              >
                <td className="px-4 py-2 font-mono text-xs">{item.referrerWalletAddress}</td>
                <td className="px-4 py-2 font-mono text-xs">{item.referredWalletAddress}</td>
                <td className="px-4 py-2">{item.referredType ?? "—"}</td>
                <td className="px-4 py-2">{item.tierPercentSnapshot.toString()}%</td>
                <td className="px-4 py-2 text-neutral-500">
                  {item.verifiedAt.toLocaleDateString()}
                </td>
              </tr>
            ))}
            {batch.items.length === 0 && (
              <tr>
                <td colSpan={5} className="px-4 py-8 text-center text-neutral-500">
                  0 referrals in this batch.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
